name = "skibidi mods"
author = "JCBWLL"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f6a2abdbfa94b677a8664ac9cafadf9ad1df83a33cde5f614d20a5afbb41cccc"

[versions]
fabric = "0.16.9"
minecraft = "1.21.4"
